function dSm_dq = dSm_dq(in1,in2)
%DSM_DQ
%    DSM_DQ = DSM_DQ(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    31-Dec-2024 11:07:45

m1 = in2(1,:);
m2 = in2(2,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q2);
t3 = cos(q3);
t4 = sin(q2);
t5 = sin(q3);
dSm_dq = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-m1.*t2,-m1.*t4.*t5,-m1.*t3.*t4,0.0,0.0,0.0,0.0,-m2.*t5+m1.*t2.*t3,-m2.*t3-m1.*t2.*t5],[6,3]);
