function dSTf_dq = dSTf_dq(in1,in2)
%DSTF_DQ
%    DSTF_DQ = DSTF_DQ(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    31-Dec-2024 15:58:41

f4 = in2(4,:);
f5 = in2(5,:);
f6 = in2(6,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q2);
t3 = cos(q3);
t4 = sin(q2);
t5 = sin(q3);
dSTf_dq = reshape([0.0,0.0,0.0,-f4.*t2-f6.*t3.*t4-f5.*t4.*t5,0.0,0.0,f5.*t2.*t3-f6.*t2.*t5,-f6.*t3-f5.*t5,0.0],[3,3]);
