function jac_expr1 = jacobian_function_cpp(in1,in2)
%JACOBIAN_FUNCTION_CPP
%    JAC_EXPR1 = JACOBIAN_FUNCTION_CPP(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    27-Dec-2024 11:14:30

m1 = in2(1,:);
m2 = in2(2,:);
m3 = in2(3,:);
q1 = in1(1,:);
q2 = in1(2,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = sin(q2);
jac_expr1 = reshape([0.0,0.0,0.0,-m1.*t2-m3.*t3.*t4-m2.*t4.*t5,0.0,0.0,0.0,0.0,0.0,m2.*t2.*t3-m3.*t2.*t5,-m3.*t3-m2.*t5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,4]);
