function jac_expr1 = Sm(in1,in2)
%SM
%    JAC_EXPR1 = SM(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    30-Dec-2024 09:49:13

m1 = in2(1,:);
m2 = in2(2,:);
m3 = in2(3,:);
q1 = in1(1,:);
q2 = in1(2,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = sin(q2);
jac_expr1 = reshape([0.0,0.0,0.0,-m1.*t2-m3.*t3.*t4-m2.*t4.*t5,0.0,0.0,0.0,0.0,0.0,m2.*t2.*t3-m3.*t2.*t5,-m3.*t3-m2.*t5,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,3]);
