function jac_expr2 = STn(in1,in2)
%STN
%    JAC_EXPR2 = STN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    30-Dec-2024 11:16:53

n4 = in2(4,:);
n5 = in2(5,:);
q1 = in1(1,:);
q2 = in1(2,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = sin(q2);
jac_expr2 = reshape([-n4.*t2,-n4.*t4.*t5,-n4.*t3.*t4,0.0,-n5.*t5+n4.*t2.*t3,-n5.*t3-n4.*t2.*t5,0.0,0.0,0.0],[3,3]);
