function jac_expr2 = STn(in1,in2)
%STN
%    JAC_EXPR2 = STN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    30-Dec-2024 11:33:20

n4 = in2(4,:);
n5 = in2(5,:);
n6 = in2(6,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q2);
t3 = cos(q3);
t4 = sin(q2);
t5 = sin(q3);
jac_expr2 = reshape([0.0,0.0,0.0,-n4.*t2-n6.*t3.*t4-n5.*t4.*t5,0.0,0.0,n5.*t2.*t3-n6.*t2.*t5,-n6.*t3-n5.*t5,0.0],[3,3]);
