function J_back_ft = jac_ba_ft(q1,q2,q3,q4,q5,q6,q7)
%JAC_BA_FT
%    J_BACK_FT = JAC_BA_FT(Q1,Q2,Q3,Q4,Q5,Q6,Q7)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    19-Jan-2023 17:11:41

t2 = cos(q3);
t3 = cos(q6);
t4 = cos(q7);
t5 = sin(q3);
t6 = sin(q6);
t7 = sin(q7);
t8 = t3.*t4;
t9 = t3.*t7;
t10 = t4.*t6;
t11 = t6.*t7;
t13 = t6.*(2.09e+2./1.0e+3);
t15 = t2.*t3.*(2.09e+2./1.0e+3);
t16 = t3.*t5.*(2.09e+2./1.0e+3);
t12 = -t11;
t14 = t9+t10;
t18 = -t15;
t19 = t13+1.9e+1./1.0e+2;
t17 = t8+t12;
t20 = t2.*t14.*(3.9e+1./2.0e+2);
t21 = t5.*t14.*(3.9e+1./2.0e+2);
t22 = t2.*t17.*(3.9e+1./2.0e+2);
t23 = t5.*t17.*(3.9e+1./2.0e+2);
t24 = -t22;
J_back_ft = reshape([1.0,0.0,0.0,1.0,t18+t21+t24+t5.*t19,t16+t20+t23+t2.*t19,0.0,0.0,0.0,0.0,t18+t21+t24+t5.*t13,t16+t20+t23+t2.*t13,t21+t24,t20+t23],[2,7]);
