function Jdqd_front_ft_FO_v = Jdqd_fr_ft_FO_v(q1,q2,q3,q4,q5,q6,q7,qd1,qd2,qd3,qd4,qd5,qd6,qd7)
%JDQD_FR_FT_FO_V
%    JDQD_FRONT_FT_FO_V = JDQD_FR_FT_FO_V(Q1,Q2,Q3,Q4,Q5,Q6,Q7,QD1,QD2,QD3,QD4,QD5,QD6,QD7)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    19-Jan-2023 17:11:43

t2 = cos(q3);
t3 = cos(q4);
t4 = cos(q5);
t5 = sin(q3);
t6 = sin(q4);
t7 = sin(q5);
t8 = t3.*t4;
t9 = t3.*t7;
t10 = t4.*t6;
t11 = t6.*t7;
t13 = t6.*(2.09e+2./1.0e+3);
t15 = t2.*t3.*(2.09e+2./1.0e+3);
t17 = t3.*t5.*(2.09e+2./1.0e+3);
t20 = t5.*t6.*(-2.09e+2./1.0e+3);
t12 = -t11;
t14 = t9+t10;
t16 = t2.*t13;
t18 = t5.*t13;
t21 = t13-1.9e+1./1.0e+2;
t19 = t8+t12;
t22 = t2.*t14.*(3.9e+1./2.0e+2);
t23 = t5.*t14.*(3.9e+1./2.0e+2);
t24 = -t23;
t25 = t2.*t19.*(3.9e+1./2.0e+2);
t26 = t5.*t19.*(3.9e+1./2.0e+2);
t27 = t22+t26;
t28 = t24+t25;
t30 = qd5.*(t23-t25).*-2.0;
t29 = qd5.*t27.*2.0;
t31 = t16+t17+t27;
t32 = t15+t20+t28;
t33 = qd4.*t31.*2.0;
t34 = qd4.*t32.*2.0;
Jdqd_front_ft_FO_v = reshape([0.0,0.0,0.0,0.0,t29+t33+qd3.*(t17+t27+t2.*t21).*2.0,t30+t34+qd3.*(t15+t28-t5.*t21).*2.0,t29+t33+qd3.*t31.*2.0,t30+t34+qd3.*t32.*2.0,t29+qd3.*t27.*2.0+qd4.*t27.*2.0,t30-qd3.*(t23-t25).*2.0-qd4.*(t23-t25).*2.0,0.0,0.0,0.0,0.0],[2,7]);
